title = ""

[characters]
[characters.brain]
name = "brain"
image = "brain.ong"

[characters.you]
name = "you"
image = "you.ong"

[scenes]
[scenes.start]
type = "text"
who = "brain"
next = "img"
message = """
  I've been waiting for you!
"""

[scenes.img]
type = 'image'
who = "brain"
width = 400
pixel-art = true
next = "wow"

[scenes.wow]
type = "text"
who = "you"
next = "done"
message = """
  no way!
"""

[scenes.tests]
type = "choices"
who = "you"
choices = [
  ["pretend you've not seen him", "scene.id"],
  ["pretend you've not seen him", "scene.id"],
]